### ISSUE TITLE
Integrate Spline with Pyspark

### ISSUE THREAD

**Issue by Jainit25** [AbsaOSS/spline#389]
I am able to write the lineage to mongo using scala and trying to do the same using pyspark on a different cluster. I am using pyspark on Databricks notebook (spark 2.4.3, scala 2.11) and following python_sample.py as a reference.
I have used `mvn package -P spark-2.4,shade` and uploaded the jar to cluster libraries. I am not able to see any lineage in mongoDB. I am not sure what am I missing or doing wrong here. Please advise. 
The following is the python code and the spark configs: 

python notebook code

```
from pyspark.sql import SparkSession
from pyspark.sql import functions as F

spark = SparkSession.builder \
    .appName("spline_app")\
    .config("spark.jars", "dbfs:/path_where_the_jar_is_uploaded")\
    .getOrCreate()

sc = spark.sparkContext
sc.setSystemProperty("spark.jars", "dbfs:/path_where_the_jar_is_uploaded")
sc.setSystemProperty("spline.persistence.factory","za.co.absa.spline.persistence.mongo.MongoPersistenceFactory")
sc.setSystemProperty("spline.mongodb.name", "mongodb-name")
sc.setSystemProperty("spline.mode", "REQUIRED")
sc.setSystemProperty("spline.mongodb.url", "mongodb_url")

jvm = sc._jvm
sc._jvm.za.co.absa.spline.core.SparkLineageInitializer.enableLineageTracking(spark._jsparkSession)

spark.read\
  .option("header", "true")\
  .option("inferschema", "true")\
  .csv("/FileStore/tables/SalesJan2009.csv")\
  .select("Product", "Price", "Country")\
  .groupBy("Country")\
  .agg(F.count("*").alias("cnt"))\
  .write.mode('overwrite')\
  .parquet("/FileStore/tables/spline_test.parquet")
```

spark configs:
```
spline.mongodb.name mongodb-name
spline.persistence.factory za.co.absa.spline.persistence.mongo.MongoPersistenceFactory
spline.mongodb.url mongodb://mongodb_url
spark.databricks.delta.preview.enabled true
spline.mode REQUIRED
spline.jars dbfs:/path_where_the_jar_is_uploaded
```

**Comment by Jainit25** [comment]
@wajda I could make it working with Spark-2.2.1, Scala-2.11 and Pyspark-2.2.1 on Databricks using the instructions from https://github.com/AbsaOSS/spline/blob/release/0.3/sample/src/main/scala/za/co/absa/spline/sample/batch/python_sample.py.
However, I am getting this error when trying with Spark-2.4.3 Scala-2.11 and Pyspark-2.4.3. I'd really appreciate if you could advise me to make it working for 2.4.3.
```log4j:WARN No appenders could be found for logger (com.databricks.conf.trusted.ProjectConf$).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
Mon Oct 21 00:37:42 2019 py4j imported
Mon Oct 21 00:37:42 2019 Python shell started with PID  2724  and guid  bc2b192232694e86b251a71e95a1540f
Mon Oct 21 00:37:42 2019 Python shell executor start
sh: 1: pyspark: not found
java.lang.NoClassDefFoundError: scala/tools/scalap/scalax/rules/scalasig/ByteCode$
	at salat.util.ScalaSigUtil$.parseClassFileFromByteCode(ScalaSigUtil.scala:39)
	at salat.util.ScalaSigUtil$.parseScalaSig0(ScalaSigUtil.scala:83)
	at salat.ClassAnalyzer$.findSym(ClassAnalyzer.scala:46)
	at salat.ClassAnalyzer.<init>(ClassAnalyzer.scala:136)
	at salat.ConcreteGrater.ca$lzycompute(Grater.scala:120)
	at salat.ConcreteGrater.ca(Grater.scala:120)
	at salat.ConcreteGrater.useTypeHint$lzycompute(Grater.scala:124)
	at salat.ConcreteGrater.useTypeHint(Grater.scala:123)
	at salat.ConcreteGrater.asDBObject(Grater.scala:291)
	at za.co.absa.spline.persistence.mongo.MongoDataLineageWriter.store(MongoDataLineageWriter.scala:32)
	at za.co.absa.spline.core.SparkLineageProcessor$$anonfun$2.apply(SparkLineageProcessor.scala:50)
	at za.co.absa.spline.core.SparkLineageProcessor$$anonfun$2.apply(SparkLineageProcessor.scala:49)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.ClassNotFoundException: scala.tools.scalap.scalax.rules.scalasig.ByteCode$
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at com.databricks.backend.daemon.driver.ClassLoaders$LibraryClassLoader.loadClass(ClassLoaders.scala:151)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 21 more
```
So I tried installing the library `org.scala-lang:scalap:2.13.1`. But now it throws me the following error:
```
log4j:WARN No appenders could be found for logger (com.databricks.conf.trusted.ProjectConf$).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
Mon Oct 21 01:26:05 2019 py4j imported
Mon Oct 21 01:26:06 2019 Python shell started with PID  2668  and guid  44a3184b20e444bca43b642870f8b6e1
Mon Oct 21 01:26:06 2019 Python shell executor start
sh: 1: pyspark: not found
java.lang.NoClassDefFoundError: scala/collection/IterableOnce
	at salat.util.ScalaSigUtil$.parseClassFileFromByteCode(ScalaSigUtil.scala:40)
	at salat.util.ScalaSigUtil$.parseScalaSig0(ScalaSigUtil.scala:83)
	at salat.ClassAnalyzer$.findSym(ClassAnalyzer.scala:46)
	at salat.ClassAnalyzer.<init>(ClassAnalyzer.scala:136)
	at salat.ConcreteGrater.ca$lzycompute(Grater.scala:120)
	at salat.ConcreteGrater.ca(Grater.scala:120)
	at salat.ConcreteGrater.useTypeHint$lzycompute(Grater.scala:124)
	at salat.ConcreteGrater.useTypeHint(Grater.scala:123)
	at salat.ConcreteGrater.asDBObject(Grater.scala:291)
	at za.co.absa.spline.persistence.mongo.MongoDataLineageWriter.store(MongoDataLineageWriter.scala:32)
	at za.co.absa.spline.core.SparkLineageProcessor$$anonfun$2.apply(SparkLineageProcessor.scala:50)
	at za.co.absa.spline.core.SparkLineageProcessor$$anonfun$2.apply(SparkLineageProcessor.scala:49)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.ClassNotFoundException: scala.collection.IterableOnce
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at com.databricks.backend.daemon.driver.ClassLoaders$LibraryClassLoader.loadClass(ClassLoaders.scala:151)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 21 more
```

**Comment by wajda** [comment]
Seems to be a duplication for #388

**Comment by Jainit25** [comment]
@wajda The solution you provided for #388 works just fine. I am using the bundles from https://search.maven.org/search?q=spline-bundle. Thank you and really appreciate your help!
